### ISSUE TITLE
Is it a joint pipeline or are the tasks performed separately?

### ISSUE THREAD

**Issue by longshangbang** [ku21fan/COO-Comic-Onomatopoeia#3]
As titled.

Specifically, In Tab 4., link prediction results are presented. What are the inputs here? Is the m4C model taking ground truth text content and polygons as input? Or is the model taking output from the detection and recognition models as input?

**Comment by ku21fan** [comment]
Hello, 

The tasks are performed separately.
M4C model takes ground truth text content and polygon as input.

(As mentioned in section 4.1 of our paper,
"In each task, we use ground truth information rather than predicted results of other tasks.")

End-to-end link prediction (from text detection to link prediction) is not yet performed in our paper, and it is one of our future works.

Best regards
